baseurl: /R5.A.05-ProgrammationAvancee-Web
permalink: /:categories/:title

markdown: kramdown

kramdown:
  input: GFM
  parse_block_html: true
  hard_wrap: false
  syntax_highlighter: disable
  syntax_highlighter_opts:
    disable : true

livereload: true